### PR TITLE
Update stylelint and stylelint-config-standard

### PR DESCRIPTION
**Pull request by XhmikosR**
@ffoodd better discuss the issue with `currentColor` here :)

So, the question is if our supported browsers support this. Keep in mind we use the same config in v4-dev too.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Friendly ping @ffoodd :)

**Comment by ffoodd** [comment]
Sorry for the delay: could you please remind me the issue with `currentColor`? 

By reading [Stylelint's changelog](https://stylelint.io/CHANGELOG), I guess it concerns our inlined SVGs: if so, I suggest we move to lowercase as recommended by Stylelint (based on recent spec changes, however [both cases are already supported](https://caniuse.com/?search=currentcolor AFAIC).

We could set the new `camelCaseSvgKeywords` setting to `true` to avoid changing our sources, but that doesn't feel right to me.

**Comment by XhmikosR** [comment]
@ffoodd @mdo what I don't know is if all of our supported browsers support the lowercase `currentvalue` keyword. For v5, we should be fine, but for v4 I'm not sure...

Let me know how to proceed :)

**Comment by ffoodd** [comment]
Just ran [a simple test](https://codepen.io/ffoodd/full/qBVLNYE) using BrowserStack, both values work fine in IE10 and 11. In fact it seems like IE10 transforms the value (but it's using Firebug to inspect, might be the tool, too).

AFAIK this shouldn't be an issue, since CSS values are supposed to be case insensitive for the most parts. `currentColor` comes from SVG but I suspect the case never really mattered in CSS. Don't know what or how to test this further though, I didn't find any literature on the topic…

**Pull request merged**
