### PR TITLE
Remove unnecessary rules

### PR DESCRIPTION
**Pull request by ashfahan**
All of these rules are already include with same value in package extending from and are not being overide. its safe to remove them

Detail:

'declaration-block-semicolon-newline-after': 'always-multi-line'
already in stylelint-config-standard

'declaration-block-semicolon-space-after': 'always-single-line'
already in stylelint-config-standard

'declaration-no-important': true
already in stylelint-config-recommended

'length-zero-no-unit': true
already in stylelint-config-standard

'media-feature-name-no-unknown': true
already in stylelint-config-recommended

'media-feature-parentheses-space-inside': 'never'
already in stylelint-config-standard

'media-feature-range-operator-space-after': 'always'
already in stylelint-config-standard

'no-duplicate-selectors': true
already in stylelint-config-recommended

'selector-list-comma-newline-after': 'always'
already in stylelint-config-standard

'scss/at-rule-no-unknown': true
already in stylelint-config-recommended-scss

there are some null scss rules in scss file, any reason to keep them?

### CODE REVIEW

**Comment by XhmikosR** [comment]
>there are some null scss rules in scss file, any reason to keep them?

Yeah, because I want to keep track of what I want to enable later. Also, some null rules are needed for scss.

**Comment by MartijnCuppens** [comment]
Thanks @ashfahan! Did you manually compare the configs?

**Comment by ashfahan** [comment]
@MartijnCuppens yeah had to do it

**Comment by XhmikosR** [comment]
@MartijnCuppens did you also confirm the rules one by one?

**Comment by MartijnCuppens** [comment]
I just found these issues:

> 'declaration-no-important': true

Not defined in [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended/blob/master/index.js)

> 'scss/at-rule-no-unknown': true

https://github.com/kristerkari/stylelint-config-recommended-scss/blob/207bda34917d35d990da2b9e69313e1bf3654322/index.js#L7

Good call @XhmikosR

**Comment by XhmikosR** [comment]
I'm gonna double check tomorrow.

**Comment by ashfahan** [comment]
> 'declaration-no-important': true

oh sorry about that i just added it back

> Not defined in [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended/blob/master/index.js)
> 
> > 'scss/at-rule-no-unknown': true
> 

its defined at [line 8]( https://github.com/kristerkari/stylelint-config-recommended-scss/blob/207bda34917d35d990da2b9e69313e1bf3654322/index.js#L8)

**Comment by XhmikosR** [comment]
I revert the scss change for now. I also found more inherited rules we can remove; I'll make a new PR for those.

**Pull request merged**
