### PR TITLE
Set font-family-name-quotes to always-where-required

### PR DESCRIPTION
**Pull request by ffoodd**
Related to [Bootstrap's #30508](https://github.com/twbs/bootstrap/pull/30508).

### CODE REVIEW

**Comment by XhmikosR** [comment]
Don't merge this yet. I know this might be not required, we need to read the spec to confirm, since the gain is negligible.

**Comment by ffoodd** [comment]
Sure, I won't merge this by myself.

IMHO the main concern isn't filesize here but legibility and consistency:  I find it much simpler when there's no quotes at all, since they're not needed.

Duplicated references just in case:
* [Matthias Bynens wrote about "unquote font family names in CSS"](https://mathiasbynens.be/notes/unquoted-font-family) back in 2012;
* and went with [a neat tool to check wheter your font-family name requires quotes or not](https://mothereff.in/font-family);

**Comment by ffoodd** [comment]
And moreover if [#30508](https://github.com/twbs/bootstrap/pull/30508) don't get merged, this one should be closed as well.

**Comment by MartijnCuppens** [comment]
This is a BC I think, we'll need to split our stylelint configs for v4 and v5 if we merge this

**Comment by XhmikosR** [comment]
>This is a BC I think

I don't think so. This is a lint config and rules are supposed to change.

**Comment by ffoodd** [comment]
Maybe requires a backport to v4, otherwise?

**Comment by XhmikosR** [comment]
>Maybe requires a backport to v4, otherwise?

Probably, yeah, assuming the stylelint-config-twbs-bootstrap is bumped in v4-dev too. No big deal, if you ask me. 🙂

**Comment by XhmikosR** [comment]
I looked at the [spec](https://www.w3.org/TR/CSS2/fonts.html#font-family-prop) and the quotes are still recommended:

>To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens

Now, I know that in Bootstrap's case we don't have such cases AFAICT. That being said, I always prefer to err on the safe side.

**Comment by ffoodd** [comment]
Sure, this is why stylelint values are either `recommended` or `required` I guess :)

@MartijnCuppens do you agree? If so, I'll close this PR and its Bootstrap counterpart :)

**Comment by MartijnCuppens** [comment]
I'm a bit in between here, but given the negligible gains I'm eager to leave it as is.

**Pull request closed without merging**
