### PR TITLE
Add `scss/no-duplicate-mixins: true`

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
This only seems to work per file, but it's better than not enabling this I assume?

**Comment by XhmikosR** [comment]
Yup

**Comment by XhmikosR** [comment]
I guess we should make this 0.8.0. BTW eventually we should move to 1.0.0

**Comment by MartijnCuppens** [comment]
Fine by me!

**Pull request merged**
